/** @type {import('tailwindcss').Config} */
module.exports = {
    content: ['./src/**/*.{js,jsx,ts,tsx}'],
    presets: [require('nativewind/preset')],
    theme: {
        extend: {
            colors: {
                primary: 'var(--color-primary)',
                'on-primary': 'var(--color-on-primary)',
                'primary-container': 'var(--color-primary-container)',
                'on-primary-container': 'var(--color-on-primary-container)',
                secondary: 'var(--color-secondary)',
                'on-secondary': 'var(--color-on-secondary)',
                'secondary-container': 'var(--color-secondary-container)',
                'on-secondary-container': 'var(--color-on-secondary-container)',
                tertiary: 'var(--color-tertiary)',
                'on-tertiary': 'var(--color-on-tertiary)',
                'tertiary-container': 'var(--color-tertiary-container)',
                'on-tertiary-container': 'var(--color-on-tertiary-container)',
                background: 'var(--color-background)',
                'on-background': 'var(--color-on-background)',
                surface: 'var(--color-surface)',
                'on-surface': 'var(--color-on-surface)',
                'surface-variant': 'var(--color-surface-variant)',
                'on-surface-variant': 'var(--color-on-surface-variant)',
                outline: 'var(--color-outline)',
                'outline-variant': 'var(--color-outline-variant)',
                'inverse-surface': 'var(--color-inverse-surface)',
                'inverse-on-surface': 'var(--color-inverse-on-surface)',
                'inverse-primary': 'var(--color-inverse-primary)',
                error: 'var(--color-error)',
                'on-error': 'var(--color-on-error)',
                'error-container': 'var(--color-error-container)',
                'on-error-container': 'var(--color-on-error-container)',
                shadow: 'var(--color-shadow)',
                scrim: 'var(--color-scrim)',
                'surface-disabled': 'var(--color-surface-disabled)',
                'on-surface-disabled': 'var(--color-on-surface-disabled)',
                backdrop: 'var(--color-backdrop)',
                'surface-dim': 'var(--color-surface-dim)',
                'surface-bright': 'var(--color-surface-bright)',
                'surface-lowest': 'var(--color-surface-container-lowest)',
                'surface-low': 'var(--color-surface-container-low)',
                'surface-high': 'var(--color-surface-container-high)',
                'surface-highest': 'var(--color-surface-container-highest)',
                'surface-tint': 'var(--color-surface-tint)',
            },
            fontFamily: {
                'lexend-deca': ['LexendDeca'],
            },
            borderRadius: {
                '2xl': '16px',
                '3xl': '24px',
            },
            fontSize: {
                display: ['34px', { lineHeight: '40px', fontWeight: '700' }],
                'headline-lg': [
                    '28px',
                    { lineHeight: '34px', fontWeight: '600' },
                ],
                'headline-md': [
                    '24px',
                    { lineHeight: '30px', fontWeight: '600' },
                ],
                'title-lg': ['20px', { lineHeight: '26px', fontWeight: '500' }],
                'title-md': ['17px', { lineHeight: '23px', fontWeight: '500' }],
                'body-lg': ['16px', { lineHeight: '24px', fontWeight: '400' }],
                'body-md': ['14px', { lineHeight: '20px', fontWeight: '400' }],
                'label-lg': ['14px', { lineHeight: '20px', fontWeight: '500' }],
                'label-md': ['12px', { lineHeight: '16px', fontWeight: '500' }],
                'label-sm': ['11px', { lineHeight: '14px', fontWeight: '600' }],
            },
            spacing: {
                4.5: '18px',
                13: '52px',
                15: '60px',
                18: '72px',
                22: '88px',
            },
        },
    },
    plugins: [],
};
